"use client";

import { Suspense, useEffect, useState, useCallback } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import toast from "react-hot-toast";
import { ArrowRight, Sparkles, Save, Printer } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { useCurrentUser } from "@/lib/context/UserContext";
import Spinner from "@/components/ui/Spinner";
import DocumentPreview from "@/components/documents/DocumentPreview";
import {
  generateClassListData,
  generateMonthlyAttendanceData,
  generateLessonNoteData,
  generateEvaluationGridData,
} from "@/lib/documents/generators";

const AUTO_GENERATED_TYPES = [
  "class_list",
  "monthly_attendance",
  "lesson_note",
  "diagnostic_grid",
  "formative_grid",
  "summative_grid",
];

const EVAL_TYPE_BY_CODE: Record<string, string> = {
  diagnostic_grid: "diagnostic",
  formative_grid: "formative",
  summative_grid: "summative",
};

function NewDocumentForm() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const typeCode = searchParams.get("type") ?? "";

  const supabase = createClient();
  const { id: teacherId, fullName } = useCurrentUser();

  const [documentType, setDocumentType] = useState<{ id: string; label_ar: string } | null>(null);
  const [classes, setClasses] = useState<{ id: string; name: string }[]>([]);
  const [lessons, setLessons] = useState<{ id: string; objective: string }[]>([]);
  const [evaluations, setEvaluations] = useState<{ id: string; title: string }[]>([]);

  const [classId, setClassId] = useState("");
  const [lessonId, setLessonId] = useState("");
  const [evaluationId, setEvaluationId] = useState("");
  const [year, setYear] = useState(new Date().getFullYear());
  const [month, setMonth] = useState(new Date().getMonth() + 1);
  const [genericTitle, setGenericTitle] = useState("");
  const [genericNotes, setGenericNotes] = useState("");

  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [saving, setSaving] = useState(false);
  const [previewData, setPreviewData] = useState<any>(null);
  const [previewTitle, setPreviewTitle] = useState("");
  const [schoolName, setSchoolName] = useState("");

  const isAutoGenerated = AUTO_GENERATED_TYPES.includes(typeCode);
  const isEvalType = Object.keys(EVAL_TYPE_BY_CODE).includes(typeCode);

  const loadContext = useCallback(async () => {
    setLoading(true);
    const { data: type } = await supabase
      .from("document_types")
      .select("id, label_ar")
      .eq("code", typeCode)
      .maybeSingle();
    setDocumentType(type);

    const [classesRes, lessonsRes] = await Promise.all([
      supabase.from("classes").select("id, name").eq("teacher_id", teacherId).order("name"),
      typeCode === "lesson_note"
        ? supabase
            .from("lessons")
            .select("id, objective")
            .eq("teacher_id", teacherId)
            .order("created_at", { ascending: false })
        : Promise.resolve({ data: [] }),
    ]);
    setClasses(classesRes.data ?? []);
    setLessons(lessonsRes.data ?? []);

    if (isEvalType) {
      const { data: evals } = await supabase
        .from("evaluations")
        .select("id, title")
        .eq("teacher_id", teacherId)
        .eq("eval_type", EVAL_TYPE_BY_CODE[typeCode])
        .order("eval_date", { ascending: false });
      setEvaluations(evals ?? []);
    }

    setLoading(false);
  }, [supabase, teacherId, typeCode, isEvalType]);

  useEffect(() => {
    loadContext();
  }, [loadContext]);

  async function handleGenerate() {
    setGenerating(true);
    try {
      if (typeCode === "class_list") {
        if (!classId) {
          toast.error("اختر القسم أولًا");
          return;
        }
        const data = await generateClassListData(supabase, classId);
        setPreviewData(data);
        setPreviewTitle(`قائمة تلاميذ ${data.class_name}`);
        setSchoolName(data.school_name);
      } else if (typeCode === "monthly_attendance") {
        if (!classId) {
          toast.error("اختر القسم أولًا");
          return;
        }
        const data = await generateMonthlyAttendanceData(supabase, teacherId, classId, year, month);
        setPreviewData(data);
        setPreviewTitle(`كشف الحضور الشهري - ${data.class_name} - ${data.month_label}`);
        setSchoolName(data.school_name);
      } else if (typeCode === "lesson_note") {
        if (!lessonId) {
          toast.error("اختر الحصة أولًا");
          return;
        }
        const data = await generateLessonNoteData(supabase, lessonId);
        if (!data) {
          toast.error("تعذّر جلب بيانات الحصة");
          return;
        }
        setPreviewData(data);
        setPreviewTitle(`مذكرة حصة - ${data.activity_name || "بدون نشاط"}`);
        setSchoolName(data.school_name);
      } else if (isEvalType) {
        if (!evaluationId) {
          toast.error("اختر التقويم أولًا");
          return;
        }
        const data = await generateEvaluationGridData(supabase, evaluationId);
        if (!data) {
          toast.error("تعذّر جلب بيانات التقويم");
          return;
        }
        setPreviewData(data);
        setPreviewTitle(data.title);
        setSchoolName(data.school_name);
      } else {
        // نوع وثيقة عام: عنوان + محتوى حر
        if (!genericTitle.trim()) {
          toast.error("أدخل عنوان الوثيقة");
          return;
        }
        setPreviewData({ notes: genericNotes });
        setPreviewTitle(genericTitle);
        setSchoolName("");
      }
    } finally {
      setGenerating(false);
    }
  }

  async function handleSave() {
    if (!previewData || !documentType) return;
    setSaving(true);

    const { data, error } = await supabase
      .from("documents")
      .insert({
        teacher_id: teacherId,
        document_type_id: documentType.id,
        class_id: classId || null,
        title: previewTitle,
        data: previewData,
        generated_by_ai: false,
        status: "final",
      })
      .select("id")
      .single();

    setSaving(false);

    if (error || !data) {
      toast.error("تعذّر حفظ الوثيقة");
      return;
    }

    toast.success("تم حفظ الوثيقة في الأرشيف");
    router.push(`/documents/${data.id}`);
  }

  if (loading) return <Spinner />;

  if (!documentType) {
    return (
      <div className="card">
        <p className="text-center text-sm text-gray-400">نوع الوثيقة غير موجود.</p>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-3xl space-y-4">
      <button
        onClick={() => router.push("/documents")}
        className="inline-flex items-center gap-1 text-sm text-gray-500 hover:text-gray-700"
      >
        <ArrowRight size={16} />
        العودة إلى الوثائق
      </button>

      <div>
        <h1 className="text-xl font-bold">{documentType.label_ar}</h1>
        {isAutoGenerated && (
          <p className="mt-1 flex items-center gap-1 text-sm text-primary-600">
            <Sparkles size={14} />
            ستُملأ هذه الوثيقة تلقائيًا من بياناتك المسجّلة في المنصة
          </p>
        )}
      </div>

      {/* نموذج السياق */}
      <div className="card space-y-4">
        {(typeCode === "class_list" || typeCode === "monthly_attendance") && (
          <div>
            <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">
              القسم
            </label>
            <select className="input-field" value={classId} onChange={(e) => setClassId(e.target.value)}>
              <option value="">اختر القسم...</option>
              {classes.map((c) => (
                <option key={c.id} value={c.id}>
                  {c.name}
                </option>
              ))}
            </select>
          </div>
        )}

        {typeCode === "monthly_attendance" && (
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">
                السنة
              </label>
              <input
                type="number"
                className="input-field"
                value={year}
                onChange={(e) => setYear(Number(e.target.value))}
              />
            </div>
            <div>
              <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">
                الشهر
              </label>
              <input
                type="number"
                min={1}
                max={12}
                className="input-field"
                value={month}
                onChange={(e) => setMonth(Number(e.target.value))}
              />
            </div>
          </div>
        )}

        {typeCode === "lesson_note" && (
          <div>
            <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">
              الحصة
            </label>
            <select className="input-field" value={lessonId} onChange={(e) => setLessonId(e.target.value)}>
              <option value="">اختر حصة محفوظة...</option>
              {lessons.map((l) => (
                <option key={l.id} value={l.id}>
                  {l.objective}
                </option>
              ))}
            </select>
            {lessons.length === 0 && (
              <p className="mt-1 text-xs text-amber-600">
                لا توجد حصص محفوظة بعد. أنشئ حصة من Session Builder أولًا.
              </p>
            )}
          </div>
        )}

        {isEvalType && (
          <div>
            <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">
              التقويم
            </label>
            <select
              className="input-field"
              value={evaluationId}
              onChange={(e) => setEvaluationId(e.target.value)}
            >
              <option value="">اختر تقويمًا محفوظًا...</option>
              {evaluations.map((e) => (
                <option key={e.id} value={e.id}>
                  {e.title}
                </option>
              ))}
            </select>
            {evaluations.length === 0 && (
              <p className="mt-1 text-xs text-amber-600">
                لا توجد تقييمات من هذا النوع بعد. أنشئ تقويمًا من وحدة التقويم أولًا.
              </p>
            )}
          </div>
        )}

        {!isAutoGenerated && (
          <>
            <div>
              <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">
                عنوان الوثيقة *
              </label>
              <input
                className="input-field"
                value={genericTitle}
                onChange={(e) => setGenericTitle(e.target.value)}
                placeholder={documentType.label_ar}
              />
            </div>
            <div>
              <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">
                المحتوى
              </label>
              <textarea
                className="input-field min-h-[160px]"
                value={genericNotes}
                onChange={(e) => setGenericNotes(e.target.value)}
                placeholder="اكتب محتوى الوثيقة هنا..."
              />
            </div>
          </>
        )}

        <button onClick={handleGenerate} disabled={generating} className="btn-primary">
          <Sparkles size={18} className="ml-1" />
          {generating ? "جارٍ التوليد..." : "توليد المعاينة"}
        </button>
      </div>

      {/* المعاينة */}
      {previewData && (
        <>
          <div className="flex items-center justify-between print:hidden">
            <h2 className="text-base font-semibold">المعاينة</h2>
            <div className="flex gap-2">
              <button onClick={() => window.print()} className="btn-secondary w-auto px-4">
                <Printer size={16} className="ml-1" />
                طباعة
              </button>
              <button onClick={handleSave} disabled={saving} className="btn-primary w-auto px-4">
                <Save size={16} className="ml-1" />
                {saving ? "جارٍ الحفظ..." : "حفظ في الأرشيف"}
              </button>
            </div>
          </div>
          <DocumentPreview
            typeCode={typeCode}
            title={previewTitle}
            teacherName={fullName}
            schoolName={schoolName}
            data={previewData}
          />
        </>
      )}
    </div>
  );
}

export default function NewDocumentPage() {
  return (
    <Suspense fallback={<Spinner />}>
      <NewDocumentForm />
    </Suspense>
  );
}
